{{ if eq .Values.persistence.enabled true -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "foundryvtt-containerized.fullname" . }}-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "foundryvtt-containerized.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize | default "20Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "foundryvtt-containerized.fullname" . }}-install
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "foundryvtt-containerized.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.persistence.installSize | default "2Gi" }}
{{ end -}}